name: Create & Configure Infrastructure

on:
  workflow_dispatch:
    inputs:
      destroy_and_recreate:
        type: boolean
        description: Destroy and recreate the environment 
        required: false
        default: false
      destroy:
        type: boolean
        description: Destroy the environment
        required: false
        default: false


jobs:

  infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    outputs:
      instance_id: ${{ steps.get_instance_id.outputs.stdout }}

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Init Terraform
        working-directory: deployment_infra
        run: terraform init -backend-config="access_key=${{ secrets.WC_TF_AWS_ACCESS_KEY }}" -backend-config="secret_key=${{ secrets.WC_TF_AWS_SECRET_KEY }}"

      - name: Destroy Infra
        if: ${{ github.event.inputs.destroy_and_recreate == 'true' || github.event.inputs.destroy == 'true' }}
        working-directory: deployment_infra
        run: | 
          terraform destroy -no-color -auto-approve \
          -var="aws_access_key=${{ secrets.WC_TF_AWS_ACCESS_KEY }}" \
          -var="aws_secret_key=${{ secrets.WC_TF_AWS_SECRET_KEY }}" \
          -var="password=${{ secrets.WC_SSH_PASSWORD }}"

      - name: Apply Terraform
        id: tf_apply  
        if: ${{ github.event.inputs.destroy == 'false' }}
        working-directory: deployment_infra
        run: | 
          terraform apply -no-color -auto-approve \
          -var="aws_access_key=${{ secrets.WC_TF_AWS_ACCESS_KEY }}" \
          -var="aws_secret_key=${{ secrets.WC_TF_AWS_SECRET_KEY }}" \
          -var="password=${{ secrets.WC_SSH_PASSWORD }}"
      - id: get_instance_id
        working-directory: deployment_infra
        run: terraform output -raw instance_id
  

  configure_vm:
    needs: [infrastructure]
    if: ${{ github.event.inputs.destroy == 'false' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: us-east-1
          aws-access-key-id: "${{ secrets.WC_TF_AWS_ACCESS_KEY }}"
          aws-secret-access-key: "${{ secrets.WC_TF_AWS_SECRET_KEY }}"
          instance-ids: ${{ needs.infrastructure.outputs.instance_id }}

          working-directory: /home/ec2-user
          command: | 
            sudo su
            yum update -y
            yum install docker -y
            usermod -a -G docker ec2-user
            newgrp docker
            systemctl enable docker.service
            systemctl start docker.service
            amazon-linux-extras enable docker
            yum install amazon-ecr-credential-helper -y
            mkdir -p ~/.docker/
            export AWS_ECR_DISABLE_CACHE=true
            echo "{ \"credsStore\": \"ecr-login\" }" > ~/.docker/config.json
            systemctl restart docker.service
          comment: Install Docker and Set Registry Authentication Helper
      - run: echo "## Add this to the repositroy secrets **WC_EC2_INSTANCE_ID = ${{ needs.infrastructure.outputs.instance_id }}**" >> $GITHUB_STEP_SUMMARY
